// log in as Troels
POST https://localhost:7093/auth/login
Content-Type: application/json

{ "UserName" : "trmo", "Password" : "onetwo3FOUR"}

### // log in as Jakob
POST https://localhost:7093/auth/login
Content-Type: application/json

{ "UserName" : "jknr", "Password" : "password" }


### // checks if it can save



POST https://localhost:7093/auth/register
Content-Type: application/json

{ "UserName" : "adf", "Password" : "ssword", "Id": 1 }



### // login with the save
POST https://localhost:7093/auth/login
Content-Type: application/json

{ "UserName" : "adf", "Password" : "onetwo3FOUR", "Id": 1 }

### // allow anonymous
GET https://localhost:7093/test/allowanon

### // must be authorized
GET https://localhost:7093/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyNzhlZmE4Yy03MjVmLTQzNjEtODNiMi04N2I2MjQyZGNmODUiLCJpYXQiOiIxNS0xMS0yMDIyIDE0OjUwOjE5IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJleHAiOjE2Njg1Mjc0MTksImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.gZx43QyXmbDjs3FuUa0v3BAcVw7dltkX_TJoikOQByGt_y8A62KTD1Cpl0PkYMyz54XF0eB5eK6_FH6xT5R7kw




###     // policy mustbevia allowed
GET https://localhost:7093/test/mustbevia
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiIyMzYwYWZjNC01ZDQ4LTRlNTctOGYxZC0wYmZlZTFkOWM3ZjIiLCJpYXQiOiIwNi8xMC8yMDIyIDExOjE1OjQxIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoidmlhIiwiU2VjdXJpdHlMZXZlbCI6IjIiLCJleHAiOjE2NjUwNTg1NDEsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.R1pVBYWQyX_u6W6jJKf2fyVHJvtum3CDgQP3X3otDEI7fQNKZ2yMMA1Pq2Pe5WujGuO0R8nNuqSnVrmL7r8Thg

###  // policy be authorized
GET  https://localhost:7093/test/authorized
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI4NWFhODE4Zi1mN2I4LTQ2NjAtYjU1MS03YWFjYWRiMjg5MTQiLCJpYXQiOiIxNS0xMS0yMDIyIDEzOjIwOjMyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InRybW8iLCJleHAiOjE2Njg1MjIwMzIsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.1oBl25px1zOEfA9SqDik9qs_RyhmIMWYAa4w-OU2KP9GKzmvwk4-MVxy2WWSso9ewRsXI0dLoW2okhpC3P5J-A


###    // manual checking MustBeTeacher
GET https://localhost:7093/test/manualcheck
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiJkY2JlNTU4Yi1hZjBlLTRmNWUtYWIyNC0wNjBiYzUyZWUxNTkiLCJpYXQiOiIwNy8wOC8yMDIyIDA5OjQ1OjQ4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6ImprbnIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdHVkZW50IiwiRGlzcGxheU5hbWUiOiJKYWtvYiBSYXNtdXNzZW4iLCJFbWFpbCI6Impha29iQGdtYWlsLmNvbSIsIkFnZSI6IjM0IiwiRG9tYWluIjoiZ21haWwiLCJleHAiOjE2NTk4NjkxNDgsImlzcyI6IkpXVEF1dGhlbnRpY2F0aW9uU2VydmVyIiwiYXVkIjoiSldUU2VydmljZUJsYXpvcldhc21DbGllbnQifQ.3CmYYv_IN9VKHJCLVhyU_y-NNuXO38_TfIoypLdLTTa9QAEbSLdO9h9e2RHIvEIcqJBXScKTLBxwPhihj0obwA





